### ISSUE TITLE
No .exe in repository

### ISSUE THREAD

**Issue by NobbyNibbler** [tomkha/nq-miner#4]
am unable to start the miner due to it not being in the repository:

"------------------------START Miner----------------------"
'nq-miner.exe' is not recognized as an internal or external command,
operable program or batch file.
"------------------------END Miner----------------------"
"Something went wrong or you exited"
Press any key to continue . . .

**Comment by Albermonte** [comment]
You need to download from the [release page](https://github.com/tomkha/nq-miner/releases/latest) or build the repo on your own, I would recommend the first option since it's pretty straight forward
